[package]
name = "whisk"
version = "0.13.0"
license = "Apache-2.0 OR BSL-1.0 OR MIT"
description = "Simple and fast lockless async channels"
repository = "https://github.com/ardaku/whisk"
documentation = "https://docs.rs/whisk"
homepage = "https://github.com/ardaku/whisk/blob/stable/CHANGELOG.md"
include = [
    "/LICENSE_APACHE",
    "/LICENSE_BOOST",
    "/LICENSE_MIT",
    "/README.md",
    "/src/*",
    "/examples/tokio.rs",
]
categories = [
    "asynchronous",
    "concurrency",
    "embedded",
    "hardware-support",
    "no-std",
]
keywords = ["channel", "actor", "mpmc", "notifier", "event_iterator"]
readme = "README.md"
edition = "2024"
rust-version = "1.95"

[[example]]
name = "tokio"
required-features = ["futures_core_3"]

[dependencies.futures_core_3]
package = "futures-core"
version = "0.3.33"
optional = true
default-features = false

[dependencies.event_iterator]
version = "0.1.0"
optional = true

[dev-dependencies]
async_main = { version = "0.4.0", features = ["pasts"] }
dl_api = "0.4.0"
flume = "0.12.0"
futures = "0.3.33"
libm = "0.2.16"
ntest = "0.10.0"
tokio-stream = "0.1.18"

[dev-dependencies.pasts]
version = "0.14.3"
default-features = false

[dev-dependencies.tokio]
version = "1.53.1"
default-features = false
features = ["rt-multi-thread", "macros"]

[features]
default = []

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[package.metadata.docs.rs]
all-features = true
